version: '3'
services:
  web:
    build: .
    ports:
      - '80:80'
  db:
    image: 'postgres:14.7'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'p@ssw0rd'
      POSTGRES_USER: 'app'
      POSTGRES_DB: 'app'
    volumes:
      - './dev/db/initdb:/docker-entrypoint-initdb.d'
